Repository CoDEVumc/CoDEV_BackEnd, pull requests merged in 2023-03, with the labels that each got.

#263 [Feat/#262]: 커뮤니티 게시판 domain 및 파일 구조 생성
  src/main/java/com/codevumc/codev_backend/controller/co_infoboard/CoInfoBoardController.java
  src/main/java/com/codevumc/codev_backend/controller/co_qnaboard/CoQnaBoardController.java
  src/main/java/com/codevumc/codev_backend/domain/CoCommentOfInfoBoard.java
  src/main/java/com/codevumc/codev_backend/domain/CoCommentOfQnaBoard.java
  src/main/java/com/codevumc/codev_backend/domain/CoInfoBoard.java
  src/main/java/com/codevumc/codev_backend/domain/CoLikeOfInfoBoard.java
  src/main/java/com/codevumc/codev_backend/domain/CoLikeOfQnaBoard.java
  src/main/java/com/codevumc/codev_backend/domain/CoMarkOfInfoBoard.java
  src/main/java/com/codevumc/codev_backend/domain/CoMarkOfQnaBoard.java
  src/main/java/com/codevumc/codev_backend/domain/CoQnaBoard.java
  src/main/java/com/codevumc/codev_backend/domain/CoReCommentOfInfoBoard.java
  src/main/java/com/codevumc/codev_backend/domain/CoReCommentOfQnaBoard.java
  src/main/java/com/codevumc/codev_backend/mapper/CoInfoBoardMapper.java
  src/main/java/com/codevumc/codev_backend/mapper/CoQnaBoardMapper.java
  src/main/java/com/codevumc/codev_backend/service/co_infoboard/CoInfoBoardService.java
  src/main/java/com/codevumc/codev_backend/service/co_infoboard/CoInfoBoardServiceImpl.java
  src/main/java/com/codevumc/codev_backend/service/co_qnaboard/CoQnaBoardService.java
  src/main/java/com/codevumc/codev_backend/service/co_qnaboard/CoQnaBoardServiceImpl.java
  src/main/resources/com/codevumc/codev_backend/mapper/CoInfoBoardMapper.xml
  src/main/resources/com/codevumc/codev_backend/mapper/CoQnaBoardMapper.xml
Labels: Feat, 데런/김대현

#265 [Feat/#264] 게시판 글쓰기 (사진) 추가
  src/main/java/com/codevumc/codev_backend/controller/co_infoboard/CoInfoBoardController.java
  src/main/java/com/codevumc/codev_backend/controller/co_qnaboard/CoQnaBoardController.java
  src/main/java/com/codevumc/codev_backend/domain/CoInfoBoard.java
  src/main/java/com/codevumc/codev_backend/domain/CoQnaBoard.java
  src/main/java/com/codevumc/codev_backend/mapper/CoInfoBoardMapper.java
  src/main/java/com/codevumc/codev_backend/mapper/CoQnaBoardMapper.java
  src/main/java/com/codevumc/codev_backend/service/co_infoboard/CoInfoBoardService.java
  src/main/java/com/codevumc/codev_backend/service/co_infoboard/CoInfoBoardServiceImpl.java
  src/main/java/com/codevumc/codev_backend/service/co_project/CoProjectServiceImpl.java
  src/main/java/com/codevumc/codev_backend/service/co_qnaboard/CoQnaBoardService.java
  src/main/java/com/codevumc/codev_backend/service/co_qnaboard/CoQnaBoardServiceImpl.java
  src/main/resources/com/codevumc/codev_backend/mapper/CoInfoBoardMapper.xml
  src/main/resources/com/codevumc/codev_backend/mapper/CoQnaBoardMapper.xml
Labels: Feat, 데런/김대현

#268 [Feat/#267] 질문댓글달기
  src/main/java/com/codevumc/codev_backend/controller/co_qnaboard/CoQnaBoardController.java
  src/main/java/com/codevumc/codev_backend/mapper/CoQnaBoardMapper.java
  src/main/java/com/codevumc/codev_backend/service/co_qnaboard/CoQnaBoardService.java
  src/main/java/com/codevumc/codev_backend/service/co_qnaboard/CoQnaBoardServiceImpl.java
  src/main/resources/com/codevumc/codev_backend/mapper/CoQnaBoardMapper.xml
Labels: Feat, 헤더/이해송

#273 [Feat/#269] 정보 댓글 달기
  src/main/java/com/codevumc/codev_backend/controller/co_infoboard/CoInfoBoardController.java
  src/main/java/com/codevumc/codev_backend/controller/co_qnaboard/CoQnaBoardController.java
  src/main/java/com/codevumc/codev_backend/mapper/CoInfoBoardMapper.java
  src/main/java/com/codevumc/codev_backend/service/co_infoboard/CoInfoBoardService.java
  src/main/java/com/codevumc/codev_backend/service/co_infoboard/CoInfoBoardServiceImpl.java
  src/main/resources/com/codevumc/codev_backend/mapper/CoInfoBoardMapper.xml
Labels: Feat, 헤더/이해송

#272 [Feat/#270] 질문 대댓글 작성 api 추가
  src/main/java/com/codevumc/codev_backend/controller/co_qnaboard/CoQnaBoardController.java
  src/main/java/com/codevumc/codev_backend/mapper/CoQnaBoardMapper.java
  src/main/java/com/codevumc/codev_backend/service/co_qnaboard/CoQnaBoardService.java
  src/main/java/com/codevumc/codev_backend/service/co_qnaboard/CoQnaBoardServiceImpl.java
  src/main/resources/com/codevumc/codev_backend/mapper/CoQnaBoardMapper.xml
Labels: Feat, 민규/김민규

#276 [Feat/#271] 정보 게시판 대댓글 api 추가
  src/main/java/com/codevumc/codev_backend/controller/co_infoboard/CoInfoBoardController.java
  src/main/java/com/codevumc/codev_backend/mapper/CoInfoBoardMapper.java
  src/main/java/com/codevumc/codev_backend/service/co_infoboard/CoInfoBoardService.java
  src/main/java/com/codevumc/codev_backend/service/co_infoboard/CoInfoBoardServiceImpl.java
  src/main/resources/com/codevumc/codev_backend/mapper/CoInfoBoardMapper.xml
Labels: Feat, 민규/김민규

#275 [Feat/#274] 질문/정보 게시판 북마크
  src/main/java/com/codevumc/codev_backend/controller/co_infoboard/CoInfoBoardController.java
  src/main/java/com/codevumc/codev_backend/controller/co_qnaboard/CoQnaBoardController.java
  src/main/java/com/codevumc/codev_backend/mapper/CoInfoBoardMapper.java
  src/main/java/com/codevumc/codev_backend/mapper/CoQnaBoardMapper.java
  src/main/java/com/codevumc/codev_backend/service/co_infoboard/CoInfoBoardService.java
  src/main/java/com/codevumc/codev_backend/service/co_infoboard/CoInfoBoardServiceImpl.java
  src/main/java/com/codevumc/codev_backend/service/co_qnaboard/CoQnaBoardService.java
  src/main/java/com/codevumc/codev_backend/service/co_qnaboard/CoQnaBoardServiceImpl.java
  src/main/resources/com/codevumc/codev_backend/mapper/CoInfoBoardMapper.xml
  src/main/resources/com/codevumc/codev_backend/mapper/CoQnaBoardMapper.xml
Labels: Feat, 헤더/이해송

#279 [Feat/#261] 질문게시판 상세조회
  src/main/java/com/codevumc/codev_backend/controller/co_qnaboard/CoQnaBoardController.java
  src/main/java/com/codevumc/codev_backend/domain/CoCommentOfQnaBoard.java
  src/main/java/com/codevumc/codev_backend/domain/CoQnaBoard.java
  src/main/java/com/codevumc/codev_backend/mapper/CoQnaBoardMapper.java
  src/main/java/com/codevumc/codev_backend/service/co_qnaboard/CoQnaBoardService.java
  src/main/java/com/codevumc/codev_backend/service/co_qnaboard/CoQnaBoardServiceImpl.java
  src/main/resources/com/codevumc/codev_backend/mapper/CoQnaBoardMapper.xml
Labels: Feat, 와이지/진윤규

#284 [feat/#280] 질문게시판 상세조회
  src/main/java/com/codevumc/codev_backend/controller/co_infoboard/CoInfoBoardController.java
  src/main/java/com/codevumc/codev_backend/domain/CoCommentOfInfoBoard.java
  src/main/java/com/codevumc/codev_backend/domain/CoInfoBoard.java
  src/main/java/com/codevumc/codev_backend/mapper/CoInfoBoardMapper.java
  src/main/java/com/codevumc/codev_backend/security/SecurityConfig.java
  src/main/java/com/codevumc/codev_backend/service/co_infoboard/CoInfoBoardService.java
  src/main/java/com/codevumc/codev_backend/service/co_infoboard/CoInfoBoardServiceImpl.java
  src/main/resources/com/codevumc/codev_backend/mapper/CoInfoBoardMapper.xml
Labels: Feat, 와이지/진윤규

#282 [Feat/#277] 정보/질문 게시판 전체 조회 api
  src/main/java/com/codevumc/codev_backend/controller/co_infoboard/CoInfoBoardController.java
  src/main/java/com/codevumc/codev_backend/controller/co_qnaboard/CoQnaBoardController.java
  src/main/java/com/codevumc/codev_backend/domain/CoInfoBoard.java
  src/main/java/com/codevumc/codev_backend/domain/CoQnaBoard.java
  src/main/java/com/codevumc/codev_backend/mapper/CoInfoBoardMapper.java
  src/main/java/com/codevumc/codev_backend/mapper/CoQnaBoardMapper.java
  src/main/java/com/codevumc/codev_backend/service/co_infoboard/CoInfoBoardService.java
  src/main/java/com/codevumc/codev_backend/service/co_infoboard/CoInfoBoardServiceImpl.java
  src/main/java/com/codevumc/codev_backend/service/co_qnaboard/CoQnaBoardService.java
  src/main/java/com/codevumc/codev_backend/service/co_qnaboard/CoQnaBoardServiceImpl.java
  src/main/resources/com/codevumc/codev_backend/mapper/CoInfoBoardMapper.xml
  src/main/resources/com/codevumc/codev_backend/mapper/CoQnaBoardMapper.xml
Labels: Feat, 민규/김민규

#288 [Fix/#287] : 정보게시판 목록 조회 수정 (내가쓴글 보기)
  src/main/java/com/codevumc/codev_backend/controller/co_infoboard/CoInfoBoardController.java
  src/main/java/com/codevumc/codev_backend/service/co_infoboard/CoInfoBoardService.java
  src/main/java/com/codevumc/codev_backend/service/co_infoboard/CoInfoBoardServiceImpl.java
  src/main/resources/com/codevumc/codev_backend/mapper/CoInfoBoardMapper.xml
Labels: Fix, 데런/김대현

#290 [Fix/#289] 질문 게시판 전체 조회 코드 수정
  src/main/java/com/codevumc/codev_backend/controller/co_qnaboard/CoQnaBoardController.java
  src/main/java/com/codevumc/codev_backend/service/co_infoboard/CoInfoBoardServiceImpl.java
  src/main/java/com/codevumc/codev_backend/service/co_qnaboard/CoQnaBoardService.java
  src/main/java/com/codevumc/codev_backend/service/co_qnaboard/CoQnaBoardServiceImpl.java
  src/main/resources/com/codevumc/codev_backend/mapper/CoInfoBoardMapper.xml
  src/main/resources/com/codevumc/codev_backend/mapper/CoQnaBoardMapper.xml
Labels: Fix, 민규/김민규

#291 [Feat/#285] 질문/정보게시판 댓글/대댓글삭제
  src/main/java/com/codevumc/codev_backend/controller/co_infoboard/CoInfoBoardController.java
  src/main/java/com/codevumc/codev_backend/controller/co_qnaboard/CoQnaBoardController.java
  src/main/java/com/codevumc/codev_backend/mapper/CoInfoBoardMapper.java
  src/main/java/com/codevumc/codev_backend/mapper/CoQnaBoardMapper.java
  src/main/java/com/codevumc/codev_backend/service/co_infoboard/CoInfoBoardService.java
  src/main/java/com/codevumc/codev_backend/service/co_infoboard/CoInfoBoardServiceImpl.java
  src/main/java/com/codevumc/codev_backend/service/co_qnaboard/CoQnaBoardService.java
  src/main/java/com/codevumc/codev_backend/service/co_qnaboard/CoQnaBoardServiceImpl.java
  src/main/resources/com/codevumc/codev_backend/mapper/CoInfoBoardMapper.xml
  src/main/resources/com/codevumc/codev_backend/mapper/CoQnaBoardMapper.xml
Labels: Feat, 와이지/진윤규

#292 Revert "[Feat/#285] 질문/정보게시판 댓글/대댓글삭제"
  src/main/java/com/codevumc/codev_backend/controller/co_infoboard/CoInfoBoardController.java
  src/main/java/com/codevumc/codev_backend/controller/co_qnaboard/CoQnaBoardController.java
  src/main/java/com/codevumc/codev_backend/mapper/CoInfoBoardMapper.java
  src/main/java/com/codevumc/codev_backend/mapper/CoQnaBoardMapper.java
  src/main/java/com/codevumc/codev_backend/service/co_infoboard/CoInfoBoardService.java
  src/main/java/com/codevumc/codev_backend/service/co_infoboard/CoInfoBoardServiceImpl.java
  src/main/java/com/codevumc/codev_backend/service/co_qnaboard/CoQnaBoardService.java
  src/main/java/com/codevumc/codev_backend/service/co_qnaboard/CoQnaBoardServiceImpl.java
  src/main/resources/com/codevumc/codev_backend/mapper/CoInfoBoardMapper.xml
  src/main/resources/com/codevumc/codev_backend/mapper/CoQnaBoardMapper.xml
Labels: Fix, 데런/김대현

#286 [Feat/#283] 정보/질문 게시판 삭제
  src/main/java/com/codevumc/codev_backend/controller/co_infoboard/CoInfoBoardController.java
  src/main/java/com/codevumc/codev_backend/controller/co_qnaboard/CoQnaBoardController.java
  src/main/java/com/codevumc/codev_backend/mapper/CoInfoBoardMapper.java
  src/main/java/com/codevumc/codev_backend/mapper/CoQnaBoardMapper.java
  src/main/java/com/codevumc/codev_backend/service/co_infoboard/CoInfoBoardService.java
  src/main/java/com/codevumc/codev_backend/service/co_infoboard/CoInfoBoardServiceImpl.java
  src/main/java/com/codevumc/codev_backend/service/co_qnaboard/CoQnaBoardService.java
  src/main/java/com/codevumc/codev_backend/service/co_qnaboard/CoQnaBoardServiceImpl.java
  src/main/resources/com/codevumc/codev_backend/mapper/CoInfoBoardMapper.xml
  src/main/resources/com/codevumc/codev_backend/mapper/CoQnaBoardMapper.xml
Labels: Feat, 민규/김민규

#281 [Feat/#266] 질문/정보 게시판 수정
  src/main/java/com/codevumc/codev_backend/controller/co_infoboard/CoInfoBoardController.java
  src/main/java/com/codevumc/codev_backend/controller/co_qnaboard/CoQnaBoardController.java
  src/main/java/com/codevumc/codev_backend/mapper/CoInfoBoardMapper.java
  src/main/java/com/codevumc/codev_backend/mapper/CoQnaBoardMapper.java
  src/main/java/com/codevumc/codev_backend/service/co_infoboard/CoInfoBoardService.java
  src/main/java/com/codevumc/codev_backend/service/co_infoboard/CoInfoBoardServiceImpl.java
  src/main/java/com/codevumc/codev_backend/service/co_qnaboard/CoQnaBoardService.java
  src/main/java/com/codevumc/codev_backend/service/co_qnaboard/CoQnaBoardServiceImpl.java
  src/main/resources/com/codevumc/codev_backend/mapper/CoInfoBoardMapper.xml
  src/main/resources/com/codevumc/codev_backend/mapper/CoQnaBoardMapper.xml
Labels: Feat, 헤더/이해송

#298 [Fix/#297] 누락된 nickname 추가 및 co_viewer 추가
  src/main/java/com/codevumc/codev_backend/domain/CoInfoBoard.java
  src/main/java/com/codevumc/codev_backend/domain/CoQnaBoard.java
  src/main/resources/com/codevumc/codev_backend/mapper/CoInfoBoardMapper.xml
  src/main/resources/com/codevumc/codev_backend/mapper/CoQnaBoardMapper.xml
Labels: Fix, 민규/김민규

#301 [fix/#300] 질문게시글 댓글갯수 변수명 변경및 좋아요상태 변수추가
  src/main/java/com/codevumc/codev_backend/domain/CoCommentOfInfoBoard.java
  src/main/java/com/codevumc/codev_backend/domain/CoCommentOfQnaBoard.java
  src/main/java/com/codevumc/codev_backend/domain/CoInfoBoard.java
  src/main/java/com/codevumc/codev_backend/domain/CoQnaBoard.java
  src/main/java/com/codevumc/codev_backend/domain/CoReCommentOfInfoBoard.java
  src/main/java/com/codevumc/codev_backend/domain/CoReCommentOfQnaBoard.java
  src/main/resources/com/codevumc/codev_backend/mapper/CoInfoBoardMapper.xml
  src/main/resources/com/codevumc/codev_backend/mapper/CoQnaBoardMapper.xml
Labels: Fix, 와이지/진윤규

#303 [feat/#295] 정보/질문게시글 좋아요
  src/main/java/com/codevumc/codev_backend/controller/co_infoboard/CoInfoBoardController.java
  src/main/java/com/codevumc/codev_backend/controller/co_qnaboard/CoQnaBoardController.java
  src/main/java/com/codevumc/codev_backend/domain/CoLikeOfInfoBoard.java
  src/main/java/com/codevumc/codev_backend/domain/CoLikeOfQnaBoard.java
  src/main/java/com/codevumc/codev_backend/mapper/CoInfoBoardMapper.java
  src/main/java/com/codevumc/codev_backend/mapper/CoQnaBoardMapper.java
  src/main/java/com/codevumc/codev_backend/service/co_infoboard/CoInfoBoardService.java
  src/main/java/com/codevumc/codev_backend/service/co_infoboard/CoInfoBoardServiceImpl.java
  src/main/java/com/codevumc/codev_backend/service/co_qnaboard/CoQnaBoardService.java
  src/main/java/com/codevumc/codev_backend/service/co_qnaboard/CoQnaBoardServiceImpl.java
  src/main/resources/com/codevumc/codev_backend/mapper/CoInfoBoardMapper.xml
  src/main/resources/com/codevumc/codev_backend/mapper/CoQnaBoardMapper.xml
Labels: Feat, 와이지/진윤규

#304 [Feat/#299] 정보/질문 게시판 북마크 조회 추가
  src/main/java/com/codevumc/codev_backend/controller/co_infoboard/CoInfoBoardController.java
  src/main/java/com/codevumc/codev_backend/controller/co_qnaboard/CoQnaBoardController.java
  src/main/java/com/codevumc/codev_backend/mapper/CoInfoBoardMapper.java
  src/main/java/com/codevumc/codev_backend/mapper/CoQnaBoardMapper.java
  src/main/java/com/codevumc/codev_backend/service/co_infoboard/CoInfoBoardService.java
  src/main/java/com/codevumc/codev_backend/service/co_infoboard/CoInfoBoardServiceImpl.java
  src/main/java/com/codevumc/codev_backend/service/co_qnaboard/CoQnaBoardService.java
  src/main/java/com/codevumc/codev_backend/service/co_qnaboard/CoQnaBoardServiceImpl.java
  src/main/resources/com/codevumc/codev_backend/mapper/CoInfoBoardMapper.xml
  src/main/resources/com/codevumc/codev_backend/mapper/CoQnaBoardMapper.xml
Labels: Feat, 헤더/이해송
