Repository CoDEVumc/CoDEV_BackEnd, pull requests merged in 2023-02, with the labels that each got.

#209 [feat/#204] 기술 분야 조회 및 분야별 세부 기술 조회
  src/main/java/com/codevumc/codev_backend/controller/co_category/CoCategoryController.java
  src/main/java/com/codevumc/codev_backend/domain/CoLanguage.java
  src/main/java/com/codevumc/codev_backend/domain/CoPart.java
  src/main/java/com/codevumc/codev_backend/mapper/CoCategoryMapper.java
  src/main/java/com/codevumc/codev_backend/service/co_category/CoCategoryService.java
  src/main/java/com/codevumc/codev_backend/service/co_category/CoCategoryServiceImpl.java
  src/main/resources/com/codevumc/codev_backend/mapper/CoCategoryMapper.xml
Labels: Feat, 와이지/진윤규

#211 [Fix/#210] 스터디 글 수정시 CoPartOfStudy 삭제 추가
  src/main/java/com/codevumc/codev_backend/mapper/CoStudyMapper.java
  src/main/java/com/codevumc/codev_backend/service/co_study/CoStudyServiceImpl.java
  src/main/resources/com/codevumc/codev_backend/mapper/CoStudyMapper.xml
Labels: Fix, 민규/김민규

#212 [Feat/#195] 채팅 기능 메서드 추가
  build.gradle
  src/main/java/com/codevumc/codev_backend/chat/StompHandler.java
  src/main/java/com/codevumc/codev_backend/chat/WebSocketConfig.java
  src/main/java/com/codevumc/codev_backend/chat/WebSocketEventListener.java
  src/main/java/com/codevumc/codev_backend/controller/co_chat/CoChatController.java
  src/main/java/com/codevumc/codev_backend/domain/ChatMessage.java
  src/main/java/com/codevumc/codev_backend/domain/ChatRoom.java
  src/main/java/com/codevumc/codev_backend/domain/ChatRoomOfUser.java
  src/main/java/com/codevumc/codev_backend/domain/CoChatOfUser.java
  src/main/java/com/codevumc/codev_backend/jwt/JwtTokenProvider.java
  src/main/java/com/codevumc/codev_backend/mapper/CoChatMapper.java
  src/main/java/com/codevumc/codev_backend/service/co_chat/CoChatService.java
  src/main/java/com/codevumc/codev_backend/service/co_chat/CoChatServiceImpl.java
  src/main/java/com/codevumc/codev_backend/service/co_project/CoProjectServiceImpl.java
  src/main/resources/application.properties
  src/main/resources/com/codevumc/codev_backend/mapper/CoChatMapper.xml
  src/main/resources/static/css/main.css
  src/main/resources/static/js/main.js
  src/main/resources/templates/index.html
  src/test/java/com/codevumc/codev_backend/service/co_chat/CoChatTest.java
Labels: Feat, 데런/김대현

#219 [Fix/#217] 스터디 상세조회 쿼리 수정
  src/main/java/com/codevumc/codev_backend/domain/CoStudy.java
  src/main/java/com/codevumc/codev_backend/mapper/CoStudyMapper.java
  src/main/java/com/codevumc/codev_backend/service/co_study/CoStudyServiceImpl.java
  src/main/resources/com/codevumc/codev_backend/mapper/CoStudyMapper.xml
Labels: Fix, 헤더/이해송

#222 [Refactor/#221] 스터디 조회 한방쿼리 수정
  src/main/java/com/codevumc/codev_backend/mapper/CoStudyMapper.java
  src/main/java/com/codevumc/codev_backend/service/co_study/CoStudyServiceImpl.java
  src/main/resources/com/codevumc/codev_backend/mapper/CoStudyMapper.xml
Labels: Fix, 민규/김민규

#227 [Fix/#226]:기본 배너 이미지 출력
  src/main/java/com/codevumc/codev_backend/controller/co_project/CoProjectController.java
  src/main/java/com/codevumc/codev_backend/controller/co_study/CoStudyController.java
  src/main/java/com/codevumc/codev_backend/mapper/CoPhotosMapper.java
  src/main/java/com/codevumc/codev_backend/service/co_project/CoProjectServiceImpl.java
  src/main/java/com/codevumc/codev_backend/service/co_study/CoStudyServiceImpl.java
  src/main/resources/com/codevumc/codev_backend/mapper/CoPhotosMapper.xml
Labels: Fix, 데런/김대현

#214 [Feat/#207] 스터디 지원자 조회
  src/main/java/com/codevumc/codev_backend/controller/co_study/CoStudyController.java
  src/main/java/com/codevumc/codev_backend/domain/CoApplicantsInfoOfStudy.java
  src/main/java/com/codevumc/codev_backend/mapper/CoStudyMapper.java
  src/main/java/com/codevumc/codev_backend/service/co_studyrecruit/CoStudyRecruitService.java
  src/main/java/com/codevumc/codev_backend/service/co_studyrecruit/CoStudyRecruitServiceImpl.java
  src/main/resources/com/codevumc/codev_backend/mapper/CoStudyMapper.xml
  src/test/java/com/codevumc/codev_backend/service/co_studyrecruit/CoStudyRecruitServiceImplTest.java
Labels: Feat, 한/심종한

#229 [Fix/#228]: 프로젝트 이미지 다중 출력 및 HikariCP 적용
  build.gradle
  src/main/java/com/codevumc/codev_backend/hikari/DBConfig.java
  src/main/java/com/codevumc/codev_backend/service/co_project/CoProjectServiceImpl.java
  src/main/resources/application.properties
Labels: Fix, 데런/김대현

#225 [Feat/#224] 스터디 지원자 포폴상세조회
  src/main/java/com/codevumc/codev_backend/controller/co_study/CoStudyController.java
  src/main/java/com/codevumc/codev_backend/mapper/CoStudyMapper.java
  src/main/java/com/codevumc/codev_backend/service/co_studyrecruit/CoStudyRecruitService.java
  src/main/java/com/codevumc/codev_backend/service/co_studyrecruit/CoStudyRecruitServiceImpl.java
  src/main/resources/com/codevumc/codev_backend/mapper/CoStudyMapper.xml
Labels: Feat, 와이지/진윤규

#234 [Feat/#232] 프로젝트 지원자 임시저장/취소
  src/main/java/com/codevumc/codev_backend/controller/co_project/CoProjectController.java
  src/main/java/com/codevumc/codev_backend/domain/CoTempSaveApplicants.java
  src/main/java/com/codevumc/codev_backend/mapper/CoProjectMapper.java
  src/main/java/com/codevumc/codev_backend/service/co_projectrecruit/CoProjectRecruitService.java
  src/main/java/com/codevumc/codev_backend/service/co_projectrecruit/CoProjectRecruitServiceImpl.java
  src/main/resources/com/codevumc/codev_backend/mapper/CoProjectMapper.xml
Labels: Feat, 한/심종한

#236 [Feat/#235] 회원정보 수정 추가
  src/main/java/com/codevumc/codev_backend/controller/co_mypage/CoMyPageController.java
  src/main/java/com/codevumc/codev_backend/controller/co_user/CoUserController.java
  src/main/java/com/codevumc/codev_backend/mapper/CoUserMapper.java
  src/main/java/com/codevumc/codev_backend/service/co_user/CoUserService.java
  src/main/java/com/codevumc/codev_backend/service/co_user/CoUserServiceImpl.java
  src/main/resources/com/codevumc/codev_backend/mapper/CoUserMapper.xml
Labels: Feat, 데런/김대현

#231 [Fix/#230] 스터디 지원 상태 판별 로직 수정
  src/main/java/com/codevumc/codev_backend/mapper/CoStudyMapper.java
  src/main/java/com/codevumc/codev_backend/service/co_study/CoStudyServiceImpl.java
  src/main/java/com/codevumc/codev_backend/service/co_studyrecruit/CoStudyRecruitServiceImpl.java
  src/main/resources/com/codevumc/codev_backend/mapper/CoStudyMapper.xml
Labels: Fix, 민규/김민규

#239 [Feat/#238] 스터디 지원자 임시서장/취소
  src/main/java/com/codevumc/codev_backend/controller/co_study/CoStudyController.java
  src/main/java/com/codevumc/codev_backend/mapper/CoStudyMapper.java
  src/main/java/com/codevumc/codev_backend/service/co_studyrecruit/CoStudyRecruitService.java
  src/main/java/com/codevumc/codev_backend/service/co_studyrecruit/CoStudyRecruitServiceImpl.java
  src/main/resources/com/codevumc/codev_backend/mapper/CoStudyMapper.xml
Labels: Feat, 한/심종한

#237 [Fix/#233] 프로젝트 지원시 포폴체크, 프로젝트 상태 체크
  src/main/java/com/codevumc/codev_backend/controller/co_project/CoProjectController.java
  src/main/java/com/codevumc/codev_backend/domain/CoRecruitOfProject.java
  src/main/java/com/codevumc/codev_backend/mapper/CoProjectMapper.java
  src/main/java/com/codevumc/codev_backend/service/co_projectrecruit/CoProjectRecruitService.java
  src/main/java/com/codevumc/codev_backend/service/co_projectrecruit/CoProjectRecruitServiceImpl.java
  src/main/resources/com/codevumc/codev_backend/mapper/CoProjectMapper.xml
Labels: Fix, 와이지/진윤규

#243 [feat/#241] 비밀번호변경
  src/main/java/com/codevumc/codev_backend/controller/co_user/CoUserController.java
  src/main/java/com/codevumc/codev_backend/domain/CoUser.java
  src/main/java/com/codevumc/codev_backend/mapper/CoUserMapper.java
  src/main/java/com/codevumc/codev_backend/security/SecurityConfig.java
  src/main/java/com/codevumc/codev_backend/service/co_user/CoUserService.java
  src/main/java/com/codevumc/codev_backend/service/co_user/CoUserServiceImpl.java
  src/main/resources/com/codevumc/codev_backend/mapper/CoUserMapper.xml
Labels: Feat, 와이지/진윤규

#247 [Feat/#240] 1대1 채팅 1차 구현 완료
  build.gradle
  src/main/java/com/codevumc/codev_backend/controller/co_chat/CoChatController.java
  src/main/java/com/codevumc/codev_backend/controller/co_project/CoProjectController.java
  src/main/java/com/codevumc/codev_backend/controller/co_user/CoUserController.java
  src/main/java/com/codevumc/codev_backend/domain/ChatMessage.java
  src/main/java/com/codevumc/codev_backend/domain/ChatRoom.java
  src/main/java/com/codevumc/codev_backend/domain/ChatRoomOfUser.java
  src/main/java/com/codevumc/codev_backend/mapper/CoChatMapper.java
  src/main/java/com/codevumc/codev_backend/mongo_repository/ChatMessageRepository.java
  src/main/java/com/codevumc/codev_backend/service/co_chat/CoChatService.java
  src/main/java/com/codevumc/codev_backend/service/co_chat/CoChatServiceImpl.java
  src/main/java/com/codevumc/codev_backend/service/co_file/CoFileServiceImpl.java
  src/main/java/com/codevumc/codev_backend/service/co_project/CoProjectServiceImpl.java
  src/main/java/com/codevumc/codev_backend/service/co_user/CoUserServiceImpl.java
  src/main/resources/application.properties
  src/main/resources/com/codevumc/codev_backend/mapper/CoChatMapper.xml
  src/main/resources/com/codevumc/codev_backend/mapper/CoUserMapper.xml
Labels: Feat, 데런/김대현

#246 [refactor/#242] 스터디 지원 / 지원 취소 코드 리팩토링
  src/main/java/com/codevumc/codev_backend/controller/co_project/CoProjectController.java
  src/main/java/com/codevumc/codev_backend/controller/co_study/CoStudyController.java
  src/main/java/com/codevumc/codev_backend/domain/CoRecruitOfProject.java
  src/main/java/com/codevumc/codev_backend/domain/CoRecruitOfStudy.java
  src/main/java/com/codevumc/codev_backend/mapper/CoStudyMapper.java
  src/main/java/com/codevumc/codev_backend/service/co_studyrecruit/CoStudyRecruitService.java
  src/main/java/com/codevumc/codev_backend/service/co_studyrecruit/CoStudyRecruitServiceImpl.java
  src/main/resources/com/codevumc/codev_backend/mapper/CoStudyMapper.xml
Labels: Fix, 민규/김민규

#249 [Fix/#248] 프로젝트, 스터디 지원자 조회 시 임시저장 여부 반영
  src/main/resources/com/codevumc/codev_backend/mapper/CoProjectMapper.xml
  src/main/resources/com/codevumc/codev_backend/mapper/CoStudyMapper.xml
Labels: Fix, 한/심종한

#253 [Fix/#251] 프로젝트 모집마감 수정
  src/main/java/com/codevumc/codev_backend/controller/co_project/CoProjectController.java
  src/main/java/com/codevumc/codev_backend/service/co_projectrecruit/CoProjectRecruitService.java
  src/main/java/com/codevumc/codev_backend/service/co_projectrecruit/CoProjectRecruitServiceImpl.java
Labels: Fix, 와이지/진윤규

#254 [Fix/#252] 스터디 모집 마감 코드 수정 완료
  src/main/java/com/codevumc/codev_backend/controller/co_study/CoStudyController.java
  src/main/java/com/codevumc/codev_backend/service/co_studyrecruit/CoStudyRecruitService.java
  src/main/java/com/codevumc/codev_backend/service/co_studyrecruit/CoStudyRecruitServiceImpl.java
Labels: Fix, 민규/김민규

#255 [Feat/#250] FCM Notification을 이용한 푸쉬알림
  build.gradle
  src/main/java/com/codevumc/codev_backend/chat/WebSocketConfig.java
  src/main/java/com/codevumc/codev_backend/controller/co_category/CoCategoryController.java
  src/main/java/com/codevumc/codev_backend/controller/co_chat/CoChatController.java
  src/main/java/com/codevumc/codev_backend/controller/co_file/CoFileController.java
  src/main/java/com/codevumc/codev_backend/controller/co_mypage/CoMyPageController.java
  src/main/java/com/codevumc/codev_backend/controller/co_project/CoProjectController.java
  src/main/java/com/codevumc/codev_backend/controller/co_study/CoStudyController.java
  src/main/java/com/codevumc/codev_backend/controller/co_user/CoUserController.java
  src/main/java/com/codevumc/codev_backend/controller/firebase/FirebaseController.java
  src/main/java/com/codevumc/codev_backend/domain/ChatMessage.java
  src/main/java/com/codevumc/codev_backend/domain/ChatRoomOfUser.java
  src/main/java/com/codevumc/codev_backend/domain/CoUser.java
  src/main/java/com/codevumc/codev_backend/domain/firebase/FCM.java
  src/main/java/com/codevumc/codev_backend/domain/firebase/FcmMessage.java
  src/main/java/com/codevumc/codev_backend/errorhandler/AutheniticationEntryPointHandler.java
  src/main/java/com/codevumc/codev_backend/errorhandler/ErrorCode.java
  src/main/java/com/codevumc/codev_backend/mapper/CoChatMapper.java
  src/main/java/com/codevumc/codev_backend/mapper/CoUserMapper.java
  src/main/java/com/codevumc/codev_backend/security/SecurityConfig.java
  src/main/java/com/codevumc/codev_backend/service/co_category/CoCategoryServiceImpl.java
  src/main/java/com/codevumc/codev_backend/service/co_chat/CoChatService.java
  src/main/java/com/codevumc/codev_backend/service/co_chat/CoChatServiceImpl.java
  src/main/java/com/codevumc/codev_backend/service/co_file/CoFileService.java
  src/main/java/com/codevumc/codev_backend/service/co_file/CoFileServiceImpl.java
  src/main/java/com/codevumc/codev_backend/service/co_study/CoStudyServiceImpl.java
  src/main/java/com/codevumc/codev_backend/service/co_user/CoUserService.java
  src/main/java/com/codevumc/codev_backend/service/co_user/CoUserServiceImpl.java
  src/main/java/com/codevumc/codev_backend/service/co_user/JwtService.java
  src/main/java/com/codevumc/codev_backend/service/firebase/FirebaseCloudMessageService.java
  src/main/java/com/codevumc/codev_backend/service/firebase/FirebaseCloudMessageServiceImpl.java
  src/main/resources/application.properties
  src/main/resources/com/codevumc/codev_backend/mapper/CoChatMapper.xml
  src/main/resources/com/codevumc/codev_backend/mapper/CoUserMapper.xml
  src/main/resources/firebase/firebase_service_key.json
  src/main/resources/static/css/main.css
  src/main/resources/static/js/main.js
  src/main/resources/templates/index.html
Labels: Feat, 데런/김대현

#256 [Fix]/#250] 에러 수정 및 알림 서버 리전
  src/main/java/com/codevumc/codev_backend/controller/co_chat/CoChatController.java
  src/main/java/com/codevumc/codev_backend/service/co_chat/CoChatServiceImpl.java
  src/main/java/com/codevumc/codev_backend/service/firebase/FirebaseCloudMessageServiceImpl.java
  src/main/resources/com/codevumc/codev_backend/mapper/CoStudyMapper.xml
  src/main/resources/firebase/firebase_service_key.json
Labels: Fix, 데런/김대현

#258 [Fix/#257] 변수명 수정
  src/main/java/com/codevumc/codev_backend/domain/CoApplicantsInfoOfProject.java
  src/main/java/com/codevumc/codev_backend/service/co_projectrecruit/CoProjectRecruitServiceImpl.java
Labels: Fix, 민규/김민규
