Repository CoDEVumc/CoDEV_BackEnd, pull requests merged in 2023-01, with the labels that each got.

#9 [Feat] 도메인 클래스 작성
  src/main/java/com/codevumc/codev_backend/domain/CoRecruit.java
  src/main/java/com/codevumc/codev_backend/domain/CoStudy.java
Labels: Feat, 한/심종한

#16 [Feat/#14] 깃허브 로그인 API
  build.gradle
  build/resources/main/application.properties
  build/tmp/compileJava/previous-compilation-data.bin
  src/main/java/com/codevumc/codev_backend/controller/co_user/CoUserController.java
  src/main/java/com/codevumc/codev_backend/errorhandler/AutheniticationEntryPointHandler.java
  src/main/java/com/codevumc/codev_backend/service/co_user/CoUserService.java
  src/main/java/com/codevumc/codev_backend/service/co_user/CoUserServiceImpl.java
  src/main/java/com/codevumc/codev_backend/snslogin/GitHubApi.java
Labels: Feat, 한/심종한

#28 [Feat/#27]구글 로그인 api 재추가
  src/main/java/com/codevumc/codev_backend/controller/co_user/CoUserController.java
  src/main/java/com/codevumc/codev_backend/service/co_user/CoUserService.java
  src/main/java/com/codevumc/codev_backend/service/co_user/CoUserServiceImpl.java
  src/main/java/com/codevumc/codev_backend/snslogin/GoogleApi.java
Labels: Feat, 헤더/이해송

#30 [Fix/#26] 프로젝트 글 생성 시 사용 언어 배열로 저장
  build.gradle
  src/main/java/com/codevumc/codev_backend/controller/co_project/CoProjectController.java
  src/main/java/com/codevumc/codev_backend/service/co_project/CoProjectService.java
  src/main/java/com/codevumc/codev_backend/service/co_project/CoProjectServiceImpl.java
  src/test/java/com/codevumc/codev_backend/service/co_project/CoProjectServiceTest.java
Labels: Fix, 한/심종한

#36 fix: 프로젝트 글 생성 파트입력 수정
  src/main/java/com/codevumc/codev_backend/domain/CoPart.java
  src/main/java/com/codevumc/codev_backend/mapper/CoProjectMapper.java
  src/main/java/com/codevumc/codev_backend/service/co_project/CoProjectServiceImpl.java
  src/main/resources/com/codevumc/codev_backend/mapper/CoProjectMapper.xml
Labels: Fix, 한/심종한

#42 feat: 프로젝트 상세조회
  out/production/resources/com/codevumc/codev_backend/mapper/CoProjectMapper.xml
  src/main/java/com/codevumc/codev_backend/controller/co_project/CoProjectController.java
  src/main/java/com/codevumc/codev_backend/domain/CoLanguageOfProject.java
  src/main/java/com/codevumc/codev_backend/domain/CoPartOfProject.java
  src/main/java/com/codevumc/codev_backend/domain/CoProject.java
  src/main/java/com/codevumc/codev_backend/mapper/CoProjectMapper.java
  src/main/java/com/codevumc/codev_backend/service/co_project/CoProjectService.java
  src/main/java/com/codevumc/codev_backend/service/co_project/CoProjectServiceImpl.java
  src/main/resources/com/codevumc/codev_backend/mapper/CoProjectMapper.xml
Labels: Feat, 민규/김민규

#41 [Feat/#32] 찜하기
  src/main/java/com/codevumc/codev_backend/controller/co_project/CoProjectController.java
  src/main/java/com/codevumc/codev_backend/mapper/CoProjectMapper.java
  src/main/java/com/codevumc/codev_backend/service/co_project/CoProjectServiceImpl.java
  src/main/java/com/codevumc/codev_backend/service/co_projectheart/CoProjectHeartImpl.java
  src/main/java/com/codevumc/codev_backend/service/co_projectheart/CoProjectHeartService.java
  src/main/resources/com/codevumc/codev_backend/mapper/CoProjectMapper.xml
Labels: Feat, 헤더/이해송

#43 [Feat/#35] 프로젝트 전체 게시글 조회
  src/main/java/com/codevumc/codev_backend/controller/co_project/CoProjectController.java
  src/main/java/com/codevumc/codev_backend/domain/CoProject.java
  src/main/java/com/codevumc/codev_backend/mapper/CoProjectMapper.java
  src/main/java/com/codevumc/codev_backend/service/co_project/CoProjectServiceImpl.java
  src/main/resources/com/codevumc/codev_backend/mapper/CoProjectMapper.xml
Labels: Feat, 한/심종한

#46 feat: 마이페이지 패키지 및 클래스, xml 생성
  src/main/java/com/codevumc/codev_backend/controller/co_mypage/CoMyPageController.java
  src/main/java/com/codevumc/codev_backend/mapper/CoMyPageMapper.java
  src/main/java/com/codevumc/codev_backend/service/co_mypage/CoMyPageService.java
  src/main/java/com/codevumc/codev_backend/service/co_mypage/CoMyPageServiceImpl.java
  src/main/resources/com/codevumc/codev_backend/mapper/CoMyPageMapper.xml
Labels: Feat, 민규/김민규

#48 [Fix/#44] 프로젝트 글 생성 시 사용 언어, 파트별 인원수 배열로 입력
  src/main/java/com/codevumc/codev_backend/controller/co_project/CoProjectController.java
  src/main/java/com/codevumc/codev_backend/service/co_project/CoProjectServiceImpl.java
Labels: Fix, 한/심종한

#52 feat: 포트폴리오 도메인 & 패키지 & 클래스 & xml 파일 생성
  src/main/java/com/codevumc/codev_backend/controller/co_portfolio/CoPortfolioController.java
  src/main/java/com/codevumc/codev_backend/domain/CoPortfolio.java
  src/main/java/com/codevumc/codev_backend/mapper/CoPortfolioMapper.java
  src/main/java/com/codevumc/codev_backend/service/co_portfolio/CoPortfolioService.java
  src/main/java/com/codevumc/codev_backend/service/co_portfolio/CoPortfolioServiceImpl.java
  src/main/resources/com/codevumc/codev_backend/mapper/CoPortfolioMapper.xml
Labels: Feat, 민규/김민규

#54 [Fix/#50] 프로젝트 글 상세조회 시 사진 조회 추가
  src/main/java/com/codevumc/codev_backend/controller/co_project/CoProjectController.java
  src/main/java/com/codevumc/codev_backend/service/co_project/CoProjectService.java
  src/main/java/com/codevumc/codev_backend/service/co_project/CoProjectServiceImpl.java
  src/main/resources/com/codevumc/codev_backend/mapper/CoPhotosMapper.xml
Labels: Fix, 한/심종한

#58 [Fix/#55] CoUser도메인 변수추가
  src/main/java/com/codevumc/codev_backend/domain/CoUser.java
Labels: Fix, 와이지/진윤규

#59 feat: portfolio 도메인 추가
  src/main/java/com/codevumc/codev_backend/domain/CoPortfolio.java
  src/main/java/com/codevumc/codev_backend/domain/CoStudy.java
Labels: Feat, 민규/김민규

#65 feat: CoLanguageOfPortfolio 도메인 생성
  src/main/java/com/codevumc/codev_backend/domain/CoLanguageOfPortfolio.java
Labels: Feat, 민규/김민규

#71 Fix/#69 포트폴리오 도메인 변수명 수정 및 추가
  src/main/java/com/codevumc/codev_backend/domain/CoPortfolio.java
Labels: Fix, 민규/김민규

#75 [Feat/#61] 프로젝트 글 삭제(작성자 체크 & 게시글 존재여부 체크)
  src/main/java/com/codevumc/codev_backend/controller/co_project/CoProjectController.java
  src/main/java/com/codevumc/codev_backend/mapper/CoProjectMapper.java
  src/main/java/com/codevumc/codev_backend/service/co_project/CoProjectService.java
  src/main/java/com/codevumc/codev_backend/service/co_project/CoProjectServiceImpl.java
  src/main/resources/com/codevumc/codev_backend/mapper/CoProjectMapper.xml
Labels: Feat, 한/심종한

#78 [Feat/#72] 마이페이지에서 포트폴리오 조회
  out/production/resources/com/codevumc/codev_backend/mapper/CoPortfolioMapper.xml
  out/production/resources/com/codevumc/codev_backend/mapper/CoProjectMapper.xml
  src/main/java/com/codevumc/codev_backend/controller/co_portfolio/CoPortfolioController.java
  src/main/java/com/codevumc/codev_backend/mapper/CoPortfolioMapper.java
  src/main/java/com/codevumc/codev_backend/service/co_portfolio/CoPortfolioService.java
  src/main/java/com/codevumc/codev_backend/service/co_portfolio/CoPortfolioServiceImpl.java
  src/main/resources/com/codevumc/codev_backend/mapper/CoPortfolioMapper.xml
Labels: Feat, 와이지/진윤규

#80 [Feat#60] 포트폴리오 수정
  src/main/java/com/codevumc/codev_backend/controller/co_mypage/CoMyPageController.java
  src/main/java/com/codevumc/codev_backend/mapper/CoMyPageMapper.java
  src/main/java/com/codevumc/codev_backend/service/co_mypage/CoMyPageService.java
  src/main/java/com/codevumc/codev_backend/service/co_mypage/CoMyPageServiceImpl.java
  src/main/resources/com/codevumc/codev_backend/mapper/CoMyPageMapper.xml
  src/main/resources/com/codevumc/codev_backend/mapper/CoPortfolioMapper.xml
Labels: Feat, 헤더/이해송

#83 [fix/#82] 포트폴리오 도메인 필요없는 변수 삭제
  src/main/java/com/codevumc/codev_backend/domain/CoPortfolio.java
Labels: Fix, 민규/김민규

#84 [Fix/#81] url 정리
  src/main/java/com/codevumc/codev_backend/controller/co_mypage/CoMyPageController.java
  src/main/java/com/codevumc/codev_backend/controller/co_portfolio/CoPortfolioController.java
  src/main/java/com/codevumc/codev_backend/controller/co_project/CoProjectController.java
  src/main/java/com/codevumc/codev_backend/controller/co_user/CoUserController.java
  src/main/java/com/codevumc/codev_backend/security/SecurityConfig.java
Labels: Fix, 헤더/이해송

#86 [Fix/#85] 도메인 url 수정 및 portfolio 디렉토리 수정
  src/main/java/com/codevumc/codev_backend/controller/co_mypage/CoMyPageController.java
  src/main/java/com/codevumc/codev_backend/controller/co_portfolio/CoPortfolioController.java
  src/main/java/com/codevumc/codev_backend/controller/co_project/CoProjectController.java
  src/main/java/com/codevumc/codev_backend/controller/co_user/CoUserController.java
  src/main/java/com/codevumc/codev_backend/mapper/CoMyPageMapper.java
  src/main/java/com/codevumc/codev_backend/mapper/CoPortfolioMapper.java
  src/main/java/com/codevumc/codev_backend/service/co_mypage/CoMyPageService.java
  src/main/java/com/codevumc/codev_backend/service/co_mypage/CoMyPageServiceImpl.java
  src/main/java/com/codevumc/codev_backend/service/co_portfolio/CoPortfolioService.java
  src/main/java/com/codevumc/codev_backend/service/co_portfolio/CoPortfolioServiceImpl.java
  src/main/resources/com/codevumc/codev_backend/mapper/CoMyPageMapper.xml
  src/main/resources/com/codevumc/codev_backend/mapper/CoPortfolioMapper.xml
Labels: Fix, 한/심종한

#87 [feat/#76] 포트폴리오 삭제 API 완료
  out/production/resources/com/codevumc/codev_backend/mapper/CoMyPageMapper.xml
  out/production/resources/com/codevumc/codev_backend/mapper/CoPortfolioMapper.xml
  src/main/java/com/codevumc/codev_backend/controller/co_portfolio/CoPortfolioController.java
  src/main/java/com/codevumc/codev_backend/mapper/CoPortfolioMapper.java
  src/main/java/com/codevumc/codev_backend/service/co_portfolio/CoPortfolioService.java
  src/main/java/com/codevumc/codev_backend/service/co_portfolio/CoPortfolioServiceImpl.java
  src/main/resources/com/codevumc/codev_backend/mapper/CoPortfolioMapper.xml
Labels: Feat, 민규/김민규

#89 [fix/#88] 포트폴리오 삭제 서비스 반환값 수정, 마이페이지용 포트폴리오 패키지&클래스 명 수정
  out/production/resources/com/codevumc/codev_backend/mapper/CoPortfolioMapper.xml
  src/main/java/com/codevumc/codev_backend/controller/co_mypageportfolio/CoMyPagePortfolioController.java
  src/main/java/com/codevumc/codev_backend/mapper/CoMyPagePortfolioMapper.java
  src/main/java/com/codevumc/codev_backend/service/co_mypageportfolio/CoMyPagePortfolioService.java
  src/main/java/com/codevumc/codev_backend/service/co_mypageportfolio/CoMyPagePortfolioServiceImpl.java
  src/main/resources/com/codevumc/codev_backend/mapper/CoMyPagePortfolioMapper.xml
Labels: Fix, 민규/김민규

#95 [Feat/#94]스터디, 프로젝트 지원 도메인 생성
  out/production/resources/com/codevumc/codev_backend/mapper/CoMyPagePortfolioMapper.xml
  src/main/java/com/codevumc/codev_backend/domain/CoRecruitOfProject.java
  src/main/java/com/codevumc/codev_backend/domain/CoRecruitOfStudy.java
Labels: Feat, 민규/김민규

#96 [Fix/#92] 스터디 관련 디렉토리 생성
  src/main/java/com/codevumc/codev_backend/controller/co_study/CoStudyController.java
  src/main/java/com/codevumc/codev_backend/mapper/CoStudyMapper.java
  src/main/java/com/codevumc/codev_backend/service/co_study/CoStudyServiceImpl.java
  src/main/java/com/codevumc/codev_backend/service/co_studyheart/CoStudyHeartServiceImpl.java
  src/main/resources/com/codevumc/codev_backend/mapper/CoStudyMapper.xml
Labels: Fix, 한/심종한

#99 [Fix/#98] 스터디 도메인 변수 수정
  src/main/java/com/codevumc/codev_backend/domain/CoStudy.java
Labels: Fix, 민규/김민규

#100 [Feat/#93] 스터디 찜하기
  src/main/java/com/codevumc/codev_backend/controller/co_project/CoProjectController.java
  src/main/java/com/codevumc/codev_backend/controller/co_study/CoStudyController.java
  src/main/java/com/codevumc/codev_backend/mapper/CoStudyMapper.java
  src/main/java/com/codevumc/codev_backend/service/co_projectheart/CoProjectHeartServiceImpl.java
  src/main/java/com/codevumc/codev_backend/service/co_studyheart/CoStudyHeartService.java
  src/main/java/com/codevumc/codev_backend/service/co_studyheart/CoStudyHeartServiceImpl.java
  src/main/resources/com/codevumc/codev_backend/mapper/CoStudyMapper.xml
Labels: Feat, 헤더/이해송

#101 [Feat/#90] 스터디 상세조회 API 완성
  out/production/resources/com/codevumc/codev_backend/mapper/CoPhotosMapper.xml
  out/production/resources/com/codevumc/codev_backend/mapper/CoStudyMapper.xml
  src/main/java/com/codevumc/codev_backend/controller/co_study/CoStudyController.java
  src/main/java/com/codevumc/codev_backend/domain/CoLanguageOfStudy.java
  src/main/java/com/codevumc/codev_backend/mapper/CoPhotosMapper.java
  src/main/java/com/codevumc/codev_backend/mapper/CoStudyMapper.java
  src/main/java/com/codevumc/codev_backend/service/co_study/CoStudyService.java
  src/main/java/com/codevumc/codev_backend/service/co_study/CoStudyServiceImpl.java
  src/main/resources/com/codevumc/codev_backend/mapper/CoPhotosMapper.xml
  src/main/resources/com/codevumc/codev_backend/mapper/CoStudyMapper.xml
Labels: Feat, 민규/김민규

#103 [Feat/#91] 스터디 글 작성
  src/main/java/com/codevumc/codev_backend/controller/co_study/CoStudyController.java
  src/main/java/com/codevumc/codev_backend/domain/CoStudy.java
  src/main/java/com/codevumc/codev_backend/mapper/CoStudyMapper.java
  src/main/java/com/codevumc/codev_backend/service/co_study/CoStudyService.java
  src/main/java/com/codevumc/codev_backend/service/co_study/CoStudyServiceImpl.java
  src/main/resources/com/codevumc/codev_backend/mapper/CoStudyMapper.xml
Labels: Feat, 한/심종한

#105 [Fix/#104] 스터디 글 작성시 모집인원 전달 설정
  src/main/java/com/codevumc/codev_backend/controller/co_study/CoStudyController.java
Labels: Fix, 한/심종한

#107 [fix/#106] 쿼리문 수정 및 메서드명 수정
  src/main/java/com/codevumc/codev_backend/controller/co_study/CoStudyController.java
  src/main/resources/com/codevumc/codev_backend/mapper/CoStudyMapper.xml
Labels: Fix, 민규/김민규

#112 fix: 이메일 형식 체크
  src/main/java/com/codevumc/codev_backend/service/co_user/CoUserServiceImpl.java
Labels: Fix, 데런/김대현

#114 [Fix/#113] 프로젝트 및 스터디 페이징 처리
  src/main/java/com/codevumc/codev_backend/controller/co_project/CoProjectController.java
  src/main/java/com/codevumc/codev_backend/controller/co_study/CoStudyController.java
  src/main/java/com/codevumc/codev_backend/service/ResponseService.java
  src/main/java/com/codevumc/codev_backend/service/co_project/CoProjectService.java
  src/main/java/com/codevumc/codev_backend/service/co_project/CoProjectServiceImpl.java
  src/main/java/com/codevumc/codev_backend/service/co_study/CoStudyService.java
  src/main/java/com/codevumc/codev_backend/service/co_study/CoStudyServiceImpl.java
  src/main/resources/com/codevumc/codev_backend/mapper/CoProjectMapper.xml
  src/main/resources/com/codevumc/codev_backend/mapper/CoStudyMapper.xml
Labels: Fix, 데런/김대현

#116 [fix/#115]: Security 설정 수정 및 헤더명 변경
  src/main/java/com/codevumc/codev_backend/errorhandler/ErrorCode.java
  src/main/java/com/codevumc/codev_backend/jwt/JwtTokenProvider.java
  src/main/java/com/codevumc/codev_backend/security/SecurityConfig.java
Labels: Fix, 데런/김대현

#119 [Fix/#118] 찜취소 합치기 완성
  src/main/java/com/codevumc/codev_backend/controller/co_project/CoProjectController.java
  src/main/java/com/codevumc/codev_backend/controller/co_study/CoStudyController.java
  src/main/java/com/codevumc/codev_backend/service/co_projectheart/CoProjectHeartService.java
  src/main/java/com/codevumc/codev_backend/service/co_projectheart/CoProjectHeartServiceImpl.java
  src/main/java/com/codevumc/codev_backend/service/co_studyheart/CoStudyHeartService.java
  src/main/java/com/codevumc/codev_backend/service/co_studyheart/CoStudyHeartServiceImpl.java
Labels: Fix, 헤더/이해송

#120 [Fix/#117] 프로젝트, 스터디 전체 글 조회 시 총 모집인원 조회 추가
  .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
  .github/ISSUE_TEMPLATE/FIX_REQUEST.md
  .github/ISSUE_TEMPLATE/refactor_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  src/main/java/com/codevumc/codev_backend/controller/co_project/CoProjectController.java
  src/main/java/com/codevumc/codev_backend/controller/co_study/CoStudyController.java
  src/main/java/com/codevumc/codev_backend/domain/CoProject.java
  src/main/java/com/codevumc/codev_backend/domain/CoStudy.java
  src/main/java/com/codevumc/codev_backend/mapper/CoPhotosMapper.java
  src/main/java/com/codevumc/codev_backend/service/co_file/CoFileServiceImpl.java
  src/main/java/com/codevumc/codev_backend/service/co_project/CoProjectService.java
  src/main/java/com/codevumc/codev_backend/service/co_project/CoProjectServiceImpl.java
  src/main/java/com/codevumc/codev_backend/service/co_study/CoStudyService.java
  src/main/java/com/codevumc/codev_backend/service/co_study/CoStudyServiceImpl.java
  src/main/resources/com/codevumc/codev_backend/mapper/CoPhotosMapper.xml
  src/main/resources/com/codevumc/codev_backend/mapper/CoProjectMapper.xml
  src/main/resources/com/codevumc/codev_backend/mapper/CoStudyMapper.xml
Labels: Fix, 한/심종한

#123 [Fix/#121] 회원가입 시 프로필 이미지 변경 및 파일저장경로 수정
  src/main/java/com/codevumc/codev_backend/controller/co_project/CoProjectController.java
  src/main/java/com/codevumc/codev_backend/controller/co_study/CoStudyController.java
  src/main/java/com/codevumc/codev_backend/controller/co_user/CoUserController.java
  src/main/java/com/codevumc/codev_backend/domain/CoPhotos.java
  src/main/java/com/codevumc/codev_backend/errorhandler/ErrorCode.java
  src/main/java/com/codevumc/codev_backend/mapper/CoPhotosMapper.java
  src/main/java/com/codevumc/codev_backend/mapper/CoUserMapper.java
  src/main/java/com/codevumc/codev_backend/service/co_file/CoFileService.java
  src/main/java/com/codevumc/codev_backend/service/co_file/CoFileServiceImpl.java
  src/main/java/com/codevumc/codev_backend/service/co_project/CoProjectServiceImpl.java
  src/main/java/com/codevumc/codev_backend/service/co_study/CoStudyServiceImpl.java
  src/main/java/com/codevumc/codev_backend/service/co_user/CoUserService.java
  src/main/java/com/codevumc/codev_backend/service/co_user/CoUserServiceImpl.java
  src/main/resources/application.properties
  src/main/resources/com/codevumc/codev_backend/mapper/CoPhotosMapper.xml
  src/main/resources/com/codevumc/codev_backend/mapper/CoUserMapper.xml
Labels: Fix, 데런/김대현

#125 [Feat/#122] 스터디 삭제 API 추가
  out/production/resources/application.properties
  out/production/resources/com/codevumc/codev_backend/mapper/CoProjectMapper.xml
  out/production/resources/com/codevumc/codev_backend/mapper/CoStudyMapper.xml
  src/main/java/com/codevumc/codev_backend/controller/co_study/CoStudyController.java
  src/main/java/com/codevumc/codev_backend/mapper/CoStudyMapper.java
  src/main/java/com/codevumc/codev_backend/security/SecurityConfig.java
  src/main/java/com/codevumc/codev_backend/service/co_study/CoStudyService.java
  src/main/java/com/codevumc/codev_backend/service/co_study/CoStudyServiceImpl.java
  src/main/resources/com/codevumc/codev_backend/mapper/CoStudyMapper.xml
Labels: Feat, 민규/김민규

#131 [fix/#129] 프로젝트, 스터디 조회시 자신의 이메일 조회
  src/main/java/com/codevumc/codev_backend/controller/co_project/CoProjectController.java
  src/main/java/com/codevumc/codev_backend/controller/co_study/CoStudyController.java
  src/main/java/com/codevumc/codev_backend/domain/CoProject.java
  src/main/java/com/codevumc/codev_backend/domain/CoStudy.java
  src/main/java/com/codevumc/codev_backend/service/co_project/CoProjectService.java
  src/main/java/com/codevumc/codev_backend/service/co_project/CoProjectServiceImpl.java
  src/main/java/com/codevumc/codev_backend/service/co_study/CoStudyService.java
  src/main/java/com/codevumc/codev_backend/service/co_study/CoStudyServiceImpl.java
Labels: Fix, 와이지/진윤규

#133 [Fix/#132] 스터디, 프로젝트 지원 여부 추가
  src/main/java/com/codevumc/codev_backend/mapper/CoProjectMapper.java
  src/main/java/com/codevumc/codev_backend/mapper/CoStudyMapper.java
  src/main/java/com/codevumc/codev_backend/service/co_project/CoProjectServiceImpl.java
  src/main/java/com/codevumc/codev_backend/service/co_study/CoStudyServiceImpl.java
  src/main/resources/com/codevumc/codev_backend/mapper/CoProjectMapper.xml
  src/main/resources/com/codevumc/codev_backend/mapper/CoStudyMapper.xml
Labels: Fix, 민규/김민규

#134 [Feat/#128] 프로젝트/스터디 전체 글 조회 시 인기순/최신순 필터링 처리
  src/main/java/com/codevumc/codev_backend/controller/co_project/CoProjectController.java
  src/main/java/com/codevumc/codev_backend/controller/co_study/CoStudyController.java
  src/main/java/com/codevumc/codev_backend/mapper/CoPhotosMapper.java
  src/main/java/com/codevumc/codev_backend/service/co_project/CoProjectService.java
  src/main/java/com/codevumc/codev_backend/service/co_project/CoProjectServiceImpl.java
  src/main/java/com/codevumc/codev_backend/service/co_study/CoStudyService.java
  src/main/java/com/codevumc/codev_backend/service/co_study/CoStudyServiceImpl.java
  src/main/resources/com/codevumc/codev_backend/mapper/CoPhotosMapper.xml
  src/main/resources/com/codevumc/codev_backend/mapper/CoProjectMapper.xml
  src/main/resources/com/codevumc/codev_backend/mapper/CoStudyMapper.xml
Labels: Feat, 한/심종한

#138 [Feat/#136] 스터디 지원 취소 API 추가
  src/main/java/com/codevumc/codev_backend/controller/co_study/CoStudyController.java
  src/main/java/com/codevumc/codev_backend/mapper/CoStudyMapper.java
  src/main/java/com/codevumc/codev_backend/service/co_studyrecruit/CoStudyRecruitService.java
  src/main/java/com/codevumc/codev_backend/service/co_studyrecruit/CoStudyRecruitServiceImpl.java
  src/main/resources/com/codevumc/codev_backend/mapper/CoStudyMapper.xml
Labels: Feat, 민규/김민규

#142 [Feat/#126] 프로젝트 수정 / 이미지 파일 / 분야 / 언어
  src/main/java/com/codevumc/codev_backend/controller/co_project/CoProjectController.java
  src/main/java/com/codevumc/codev_backend/mapper/CoProjectMapper.java
  src/main/java/com/codevumc/codev_backend/service/co_file/CoFileService.java
  src/main/java/com/codevumc/codev_backend/service/co_file/CoFileServiceImpl.java
  src/main/java/com/codevumc/codev_backend/service/co_project/CoProjectService.java
  src/main/java/com/codevumc/codev_backend/service/co_project/CoProjectServiceImpl.java
  src/main/resources/com/codevumc/codev_backend/mapper/CoProjectMapper.xml
Labels: Feat, 데런/김대현

#137 [Feat/#130] 찜한 모집글 조회
  src/main/java/com/codevumc/codev_backend/controller/co_mypage/CoMyPageController.java
  src/main/java/com/codevumc/codev_backend/mapper/CoMyPageMapper.java
  src/main/java/com/codevumc/codev_backend/service/co_mypage/CoMyPageService.java
  src/main/java/com/codevumc/codev_backend/service/co_mypage/CoMyPageServiceImpl.java
  src/main/resources/com/codevumc/codev_backend/mapper/CoMyPageMapper.xml
Labels: Feat, 헤더/이해송

#140 [Fix/#135] 찜하기 본인확인 추가
  src/main/java/com/codevumc/codev_backend/mapper/CoProjectMapper.java
  src/main/java/com/codevumc/codev_backend/mapper/CoStudyMapper.java
  src/main/java/com/codevumc/codev_backend/service/co_projectheart/CoProjectHeartServiceImpl.java
  src/main/java/com/codevumc/codev_backend/service/co_studyheart/CoStudyHeartServiceImpl.java
  src/main/resources/com/codevumc/codev_backend/mapper/CoProjectMapper.xml
  src/main/resources/com/codevumc/codev_backend/mapper/CoStudyMapper.xml
Labels: Fix, 헤더/이해송

#141 [Feat/#139] 스터디 지원 API 추가
  src/main/java/com/codevumc/codev_backend/controller/co_study/CoStudyController.java
  src/main/java/com/codevumc/codev_backend/domain/CoRecruitOfStudy.java
  src/main/java/com/codevumc/codev_backend/mapper/CoStudyMapper.java
  src/main/java/com/codevumc/codev_backend/service/co_studyrecruit/CoStudyRecruitService.java
  src/main/java/com/codevumc/codev_backend/service/co_studyrecruit/CoStudyRecruitServiceImpl.java
  src/main/resources/com/codevumc/codev_backend/mapper/CoStudyMapper.xml
Labels: Feat, 민규/김민규

#143 [Feat/#127] 프로젝트 지원하기
  src/main/java/com/codevumc/codev_backend/controller/co_project/CoProjectController.java
  src/main/java/com/codevumc/codev_backend/domain/CoRecruitOfProject.java
  src/main/java/com/codevumc/codev_backend/mapper/CoProjectMapper.java
  src/main/java/com/codevumc/codev_backend/service/co_project/CoProjectService.java
  src/main/java/com/codevumc/codev_backend/service/co_project/CoProjectServiceImpl.java
  src/main/resources/com/codevumc/codev_backend/mapper/CoProjectMapper.xml
Labels: Feat, 와이지/진윤규

#146 [feat/#145] 프로젝트 지원취소
  src/main/java/com/codevumc/codev_backend/controller/co_project/CoProjectController.java
  src/main/java/com/codevumc/codev_backend/mapper/CoProjectMapper.java
  src/main/java/com/codevumc/codev_backend/service/co_projectrecruit/CoProjectRecruitImpl.java
  src/main/java/com/codevumc/codev_backend/service/co_projectrecruit/CoProjectRecruitService.java
  src/main/java/com/codevumc/codev_backend/service/co_projectrecruit/CoProjectRecruitServiceImpl.java
  src/main/resources/com/codevumc/codev_backend/mapper/CoProjectMapper.xml
Labels: Feat, 와이지/진윤규

#151 fix: 프로젝트 지원중복제거
  src/main/java/com/codevumc/codev_backend/controller/co_project/CoProjectController.java
  src/main/java/com/codevumc/codev_backend/service/co_project/CoProjectService.java
  src/main/java/com/codevumc/codev_backend/service/co_project/CoProjectServiceImpl.java
  src/main/java/com/codevumc/codev_backend/service/co_projectrecruit/CoProjectRecruitService.java
  src/main/java/com/codevumc/codev_backend/service/co_projectrecruit/CoProjectRecruitServiceImpl.java
Labels: Fix, 와이지/진윤규

#155 [feat] 프로젝트 기간연장
  src/main/java/com/codevumc/codev_backend/controller/co_project/CoProjectController.java
  src/main/java/com/codevumc/codev_backend/domain/CoProject.java
  src/main/java/com/codevumc/codev_backend/mapper/CoProjectMapper.java
  src/main/java/com/codevumc/codev_backend/service/co_project/CoProjectService.java
  src/main/java/com/codevumc/codev_backend/service/co_project/CoProjectServiceImpl.java
  src/main/resources/com/codevumc/codev_backend/mapper/CoProjectMapper.xml
Labels: Feat, 와이지/진윤규

#157 [Feat/#154] 스터디 지원자 조회
  src/main/java/com/codevumc/codev_backend/controller/co_project/CoProjectController.java
  src/main/java/com/codevumc/codev_backend/controller/co_study/CoStudyController.java
  src/main/java/com/codevumc/codev_backend/mapper/CoStudyMapper.java
  src/main/java/com/codevumc/codev_backend/service/co_project/CoProjectService.java
  src/main/java/com/codevumc/codev_backend/service/co_project/CoProjectServiceImpl.java
  src/main/java/com/codevumc/codev_backend/service/co_studyrecruit/CoStudyRecruitService.java
  src/main/java/com/codevumc/codev_backend/service/co_studyrecruit/CoStudyRecruitServiceImpl.java
  src/main/resources/com/codevumc/codev_backend/mapper/CoStudyMapper.xml
Labels: Feat, 민규/김민규

#162 [Fix/#160] 지원자 조회 메시지 수정
  src/main/java/com/codevumc/codev_backend/service/co_studyrecruit/CoStudyRecruitServiceImpl.java
Labels: Fix, 민규/김민규

#167 [Feat/#158]:스터디 수정 API 작성 완료
  src/main/java/com/codevumc/codev_backend/controller/co_project/CoProjectController.java
  src/main/java/com/codevumc/codev_backend/controller/co_study/CoStudyController.java
  src/main/java/com/codevumc/codev_backend/mapper/CoStudyMapper.java
  src/main/java/com/codevumc/codev_backend/service/co_project/CoProjectServiceImpl.java
  src/main/java/com/codevumc/codev_backend/service/co_study/CoStudyService.java
  src/main/java/com/codevumc/codev_backend/service/co_study/CoStudyServiceImpl.java
  src/main/resources/com/codevumc/codev_backend/mapper/CoStudyMapper.xml
Labels: Feat, 데런/김대현

#161 [Feat/#153] 지원한 프로젝트/스터디 조회
  src/main/java/com/codevumc/codev_backend/controller/co_mypage/CoMyPageController.java
  src/main/java/com/codevumc/codev_backend/mapper/CoMyPageMapper.java
  src/main/java/com/codevumc/codev_backend/service/co_mypage/CoMyPageService.java
  src/main/java/com/codevumc/codev_backend/service/co_mypage/CoMyPageServiceImpl.java
  src/main/resources/com/codevumc/codev_backend/mapper/CoMyPageMapper.xml
Labels: Feat, 헤더/이해송

#164 [Feat/#163] 참여한 프로젝트/스터디 조회
  src/main/java/com/codevumc/codev_backend/controller/co_mypage/CoMyPageController.java
  src/main/java/com/codevumc/codev_backend/mapper/CoMyPageMapper.java
  src/main/java/com/codevumc/codev_backend/service/co_mypage/CoMyPageService.java
  src/main/java/com/codevumc/codev_backend/service/co_mypage/CoMyPageServiceImpl.java
  src/main/resources/com/codevumc/codev_backend/mapper/CoMyPageMapper.xml
Labels: Feat, 헤더/이해송

#165 [Fix/#159] 스터디 지원에서 작성자와 지원자 구분
  src/main/java/com/codevumc/codev_backend/mapper/CoStudyMapper.java
  src/main/java/com/codevumc/codev_backend/service/co_studyrecruit/CoStudyRecruitServiceImpl.java
  src/main/resources/com/codevumc/codev_backend/mapper/CoStudyMapper.xml
Labels: Fix, 민규/김민규

#169 [fix/#168] 지원,참여한 프로젝트 충돌해결
  src/main/java/com/codevumc/codev_backend/controller/co_mypage/CoMyPageController.java
  src/main/java/com/codevumc/codev_backend/mapper/CoMyPageMapper.java
  src/main/java/com/codevumc/codev_backend/service/co_mypage/CoMyPageService.java
  src/main/java/com/codevumc/codev_backend/service/co_mypage/CoMyPageServiceImpl.java
  src/main/resources/com/codevumc/codev_backend/mapper/CoMyPageMapper.xml
Labels: Fix, 헤더/이해송

#171 [Fix/#170] 작성자 지원자 판별 오류 해결
  src/main/java/com/codevumc/codev_backend/service/co_studyrecruit/CoStudyRecruitServiceImpl.java
Labels: Fix, 민규/김민규

#175 [Fix/#174] coPart 저장 누락 수정
  src/main/java/com/codevumc/codev_backend/controller/co_study/CoStudyController.java
  src/main/java/com/codevumc/codev_backend/mapper/CoStudyMapper.java
  src/main/java/com/codevumc/codev_backend/service/co_study/CoStudyServiceImpl.java
Labels: Fix, 한/심종한

#180 [Fix/#179]: 구글 로그인 수정
  src/main/java/com/codevumc/codev_backend/service/ResponseService.java
  src/main/java/com/codevumc/codev_backend/service/co_mypage/CoMyPageServiceImpl.java
  src/main/java/com/codevumc/codev_backend/service/co_user/CoUserServiceImpl.java
  src/main/java/com/codevumc/codev_backend/snslogin/GoogleApi.java
Labels: Fix, 데런/김대현

#184 [Fix/#182] 구글로그인 API 설계 수정
  src/main/java/com/codevumc/codev_backend/controller/co_user/CoUserController.java
  src/main/java/com/codevumc/codev_backend/service/co_user/CoUserService.java
  src/main/java/com/codevumc/codev_backend/service/co_user/CoUserServiceImpl.java
  src/main/java/com/codevumc/codev_backend/snslogin/GoogleApi.java
Labels: Fix, 데런/김대현

#185 [Feat/#183] 스터디 마감기한 연장 추가
  src/main/java/com/codevumc/codev_backend/controller/co_study/CoStudyController.java
  src/main/java/com/codevumc/codev_backend/domain/CoStudy.java
  src/main/java/com/codevumc/codev_backend/mapper/CoStudyMapper.java
  src/main/java/com/codevumc/codev_backend/service/co_study/CoStudyService.java
  src/main/java/com/codevumc/codev_backend/service/co_study/CoStudyServiceImpl.java
  src/main/resources/com/codevumc/codev_backend/mapper/CoStudyMapper.xml
Labels: Feat, 민규/김민규

#187 [Fix/#186] 찜하기 쿼리 수정
  src/main/java/com/codevumc/codev_backend/mapper/CoProjectMapper.java
  src/main/java/com/codevumc/codev_backend/mapper/CoStudyMapper.java
  src/main/java/com/codevumc/codev_backend/service/co_projectheart/CoProjectHeartServiceImpl.java
  src/main/java/com/codevumc/codev_backend/service/co_studyheart/CoStudyHeartServiceImpl.java
  src/main/resources/com/codevumc/codev_backend/mapper/CoProjectMapper.xml
  src/main/resources/com/codevumc/codev_backend/mapper/CoStudyMapper.xml
Labels: Fix, 데런/김대현

#189 [fix] 프로젝트 기간연장 코드수정
  src/main/java/com/codevumc/codev_backend/service/co_project/CoProjectServiceImpl.java
Labels: Fix, 와이지/진윤규

#191 [Ffeat/#190]: 서버관리자 파일업로드 기능 구현
  src/main/java/com/codevumc/codev_backend/controller/co_file/CoFileController.java
  src/main/java/com/codevumc/codev_backend/service/co_file/CoFileServiceImpl.java
Labels: Fix, 데런/김대현

#194 [Fix/#192] 구글로그인 및 깃허브 로그인 완성
  build.gradle
  src/main/java/com/codevumc/codev_backend/controller/co_user/CoUserController.java
  src/main/java/com/codevumc/codev_backend/domain/CoUser.java
  src/main/java/com/codevumc/codev_backend/mapper/CoUserMapper.java
  src/main/java/com/codevumc/codev_backend/service/co_mypage/CoMyPageServiceImpl.java
  src/main/java/com/codevumc/codev_backend/service/co_user/CoUserService.java
  src/main/java/com/codevumc/codev_backend/service/co_user/CoUserServiceImpl.java
  src/main/java/com/codevumc/codev_backend/service/co_user/JwtService.java
  src/main/java/com/codevumc/codev_backend/snslogin/GoogleApi.java
  src/main/resources/com/codevumc/codev_backend/mapper/CoMyPageMapper.xml
  src/main/resources/com/codevumc/codev_backend/mapper/CoUserMapper.xml
Labels: Fix, 데런/김대현

#199 [Feat/#198] 스터디 모집 마감 기능 추가
  src/main/java/com/codevumc/codev_backend/controller/co_study/CoStudyController.java
  src/main/java/com/codevumc/codev_backend/domain/CoStudy.java
  src/main/java/com/codevumc/codev_backend/mapper/CoStudyMapper.java
  src/main/java/com/codevumc/codev_backend/service/co_studyrecruit/CoStudyRecruitService.java
  src/main/java/com/codevumc/codev_backend/service/co_studyrecruit/CoStudyRecruitServiceImpl.java
  src/main/resources/com/codevumc/codev_backend/mapper/CoStudyMapper.xml
Labels: Feat, 민규/김민규

#203 [Feat/#202] 지역카테고리조회
  src/main/java/com/codevumc/codev_backend/controller/co_category/CoCategoryController.java
  src/main/java/com/codevumc/codev_backend/domain/CoLocation.java
  src/main/java/com/codevumc/codev_backend/mapper/CoCategoryMapper.java
  src/main/resources/com/codevumc/codev_backend/mapper/CoCategoryMapper.xml
Labels: Feat, 와이지/진윤규

#197 [Feat/#196] 이메일 중복 체크 추가
  src/main/java/com/codevumc/codev_backend/controller/co_user/CoUserController.java
  src/main/java/com/codevumc/codev_backend/mapper/CoUserMapper.java
  src/main/java/com/codevumc/codev_backend/service/co_user/CoUserService.java
  src/main/java/com/codevumc/codev_backend/service/co_user/CoUserServiceImpl.java
  src/main/resources/com/codevumc/codev_backend/mapper/CoUserMapper.xml
Labels: Feat, 민규/김민규

#205 [Feat/#200] 프로젝트 지원자 리스트 조회(파트별)
  src/main/java/com/codevumc/codev_backend/controller/co_project/CoProjectController.java
  src/main/java/com/codevumc/codev_backend/domain/CoApplicantCount.java
  src/main/java/com/codevumc/codev_backend/domain/CoApplicantInfo.java
  src/main/java/com/codevumc/codev_backend/domain/CoApplicantsInfoOfProject.java
  src/main/java/com/codevumc/codev_backend/domain/CoProject.java
  src/main/java/com/codevumc/codev_backend/mapper/CoProjectMapper.java
  src/main/java/com/codevumc/codev_backend/service/co_projectrecruit/CoProjectRecruitService.java
  src/main/java/com/codevumc/codev_backend/service/co_projectrecruit/CoProjectRecruitServiceImpl.java
  src/main/resources/com/codevumc/codev_backend/mapper/CoProjectMapper.xml
  src/test/java/com/codevumc/codev_backend/service/co_project/CoProjectServiceTest.java
  src/test/java/com/codevumc/codev_backend/service/co_projectrecruit/CoProjectRecruitServiceImplTest.java
Labels: Feat, 한/심종한

#208 [Fix/#206] 지역전체조회 서비스추가
  src/main/java/com/codevumc/codev_backend/controller/co_category/CoCategoryController.java
  src/main/java/com/codevumc/codev_backend/service/co_category/CoCategoryService.java
  src/main/java/com/codevumc/codev_backend/service/co_category/CoCategoryServiceImpl.java
Labels: Fix, 와이지/진윤규
